<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Currency;
use App\Models\Country;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currecnyLists = [
            array('Leke', 'ALL', 'Lek'),
            array('Dollars', 'USD', '$'),
            array('Afghanistan', 'AFN', '؋'),
            array('Pesos', 'ARS', '$'),
            array('Guilders', 'AWG', 'ƒ'),
            array('Dollars', 'AUD', '$'),
            array('New Manats', 'AZN', 'ман'),
            array('Dollars', 'BSD', '$'),
            array('Dollars', 'BBD', '$'),
            array('Rubles', 'BYR', 'p.'),
            array('Euro', 'EUR', '€'),
            array('Dollars', 'BZD', 'BZ$'),
            array('Dollars', 'BMD', '$'),
            array('Bolivianos', 'BOB', '$b'),
            array('Convertible Marka', 'BAM', 'KM'),
            array('Pula', 'BWP', 'P'),
            array('Leva', 'BGN', 'лв'),
            array('Reais', 'BRL', 'R$'),
            array('Pounds', 'GBP', '£'),
            array('Dollars', 'BND', '$'),
            array('Riels', 'KHR', '៛'),
            array('Dollars', 'CAD', '$'),
            array('Dollars', 'KYD', '$'),
            array('Pesos', 'CLP', '$'),
            array('Yuan Renminbi', 'CNY', '¥'),
            array('Pesos', 'COP', '$'),
            array('Colón', 'CRC', '₡'),
            array('Kuna', 'HRK', 'kn'),
            array('Pesos', 'CUP', '₱'),
            array('Koruny', 'CZK', 'Kč'),
            array('Kroner', 'DKK', 'kr'),
            array('Dollars', 'XCD', '$'),
            array('Pounds', 'EGP', '£'),
            array('Colones', 'SVC', '$'),
            array('Pounds', 'FKP', '£'),
            array('Dollars', 'FJD', '$'),
            array('Cedis', 'GHC', '¢'),
            array('Pounds', 'GIP', '£'),
            array('Quetzales', 'GTQ', 'Q'),
            array('Pounds', 'GGP', '£'),
            array('Dollars', 'GYD', '$'),
            array('Lempiras', 'HNL', 'L'),
            array('Dollars', 'HKD', '$'),
            array('Forint', 'HUF', 'Ft'),
            array('Kronur', 'ISK', 'kr'),
            array('Rupees', 'INR', '₹'),
            array('Rupiahs', 'IDR', 'Rp'),
            array('Rials', 'IRR', '﷼'),
            array('Pounds', 'IMP', '£'),
            array('New Shekels', 'ILS', '₪'),
            array('Dollars', 'JMD', 'J$'),
            array('Yen', 'JPY', '¥'),
            array('Pounds', 'JEP', '£'),
            array('Tenge', 'KZT', 'лв'),
            array('Won', 'KPW', '₩'),
            array('Won', 'KRW', '₩'),
            array('Soms', 'KGS', 'лв'),
            array('Kips', 'LAK', '₭'),
            array('Lati', 'LVL', 'Ls'),
            array('Pounds', 'LBP', '£'),
            array('Dollars', 'LRD', '$'),
            array('Switzerland Francs', 'CHF', 'CHF'),
            array('Litai', 'LTL', 'Lt'),
            array('Denars', 'MKD', 'ден'),
            array('Ringgits', 'MYR', 'RM'),
            array('Rupees', 'MUR', '₨'),
            array('Pesos', 'MXN', '$'),
            array('Tugriks', 'MNT', '₮'),
            array('Meticais', 'MZN', 'MT'),
            array('Dollars', 'NAD', '$'),
            array('Rupees', 'NPR', '₨'),
            array('Guilders', 'ANG', 'ƒ'),
            array('Dollars', 'NZD', '$'),
            array('Cordobas', 'NIO', 'C$'),
            array('Nairas', 'NGN', '₦'),
            array('Krone', 'NOK', 'kr'),
            array('Rials', 'OMR', '﷼'),
            array('Rupees', 'PKR', '₨'),
            array('Balboa', 'PAB', 'B/.'),
            array('Guarani', 'PYG', 'Gs'),
            array('Nuevos Soles', 'PEN', 'S/.'),
            array('Pesos', 'PHP', 'Php'),
            array('Zlotych', 'PLN', 'zł'),
            array('Rials', 'QAR', '﷼'),
            array('New Lei', 'RON', 'lei'),
            array('Rubles', 'RUB', 'руб'),
            array('Pounds', 'SHP', '£'),
            array('Riyals', 'SAR', '﷼'),
            array('Dinars', 'RSD', 'Дин.'),
            array('Rupees', 'SCR', '₨'),
            array('Dollars', 'SGD', '$'),
            array('Dollars', 'SBD', '$'),
            array('Shillings', 'SOS', 'S'),
            array('Rand', 'ZAR', 'R'),
            array('Rupees', 'LKR', '₨'),
            array('Kronor', 'SEK', 'kr'),
            array('Dollars', 'SRD', '$'),
            array('Pounds', 'SYP', '£'),
            array('New Dollars', 'TWD', 'NT$'),
            array('Baht', 'THB', '฿'),
            array('Dollars', 'TTD', 'TT$'),
            array('Lira', 'TRY', '₺'),
            array('Liras', 'TRL', '£'),
            array('Dollars', 'TVD', '$'),
            array('Hryvnia', 'UAH', '₴'),
            array('Pesos', 'UYU', '$U'),
            array('Sums', 'UZS', 'лв'),
            array('Bolivares Fuertes', 'VEF', 'Bs'),
            array('Dong', 'VND', '₫'),
            array('Rials', 'YER', '﷼'),
            array('Zimbabwe Dollars', 'ZWD', 'Z$'),
            array('Algerian dinar', 'DZD', 'DA'),
            array('Angolan kwanza', 'AOA', 'Kz'),
            array('Armenian dram', 'AMD', '֏'),
            array('Bahraini dinar', 'BHD', 'BD'),
            array('Bangladeshi taka', 'BDT', '৳'),
            array('West African CFA franc', 'XOF', 'CFA'),
            array('Burundian franc', 'BIF', 'FBu'),
            array('Central African CFA franc', 'XAF', 'FCFA'),
            array('Cape Verdean escudo', 'CVE', 'Esc'),
            array('Comorian franc', 'KMF', 'CF'),
            array('Djiboutian franc', 'DJF', 'Fdj'),
            array('Dominican peso', 'DOP', 'RD$'),
            array('Eritrean nakfa', 'ERN', 'Nkf'),
            array('Ethiopian birr', 'ETB', 'Br'),
            array('CFP franc', 'XPF', '₣'),
            array('Gambian dalasi', 'GMD', 'D'),
            array('Georgian lari', 'GEL', 'ლ'),
            array('Ghanaian cedi', 'GHS', 'GH₵'),
            array('Guinean franc', 'GNF', 'FG'),
            array('Iraqi dinar', 'IQD', 'ع.د'),
            array('Jordanian dinar', 'JOD', 'د.ا'),
            array('Kenyan shilling', 'KES', 'Ksh'),
            array('Kuwaiti dinar', 'KWD', 'د.ك'),
            array('Libyan dinar', 'LYD', 'ل.د'),
            array('Macanese pataca', 'MOP', 'MOP$'),
            array('Malagasy ariary', 'MGA', 'Ar'),
            array('Malawian kwacha', 'MWK', 'MK'),
            array('Maldivian rufiyaa', 'MVR', 'Rf'),
            array('Mauritanian ouguiya', 'MRO', 'UM'),
            array('Moldovan leu', 'MDL', 'L'),
            array('Moroccan dirham', 'MAD', 'MAD'),
            array('Myanmar kyat', 'MMK', 'K'),
            array('Papua New Guinean kina', 'PGK', 'K'),
            array('Rwandan franc', 'RWF', 'R₣'),
            array('Samoan tālā', 'WST', 'WS$'),
            array('São Tomé and Príncipe dobra', 'STD', 'Db'),
            array('Sierra Leonean leone', 'SLL', 'Le'),
            array('South Sudanese pound', 'SSP', '£'),
            array('Sudanese pound', 'SDG', 'ج.س'),
            array('Swazi lilangeni', 'SZL', 'L'),
            array('Tajikistani somoni', 'TJS', 'ЅM'),
            array('Tanzanian shilling', 'TZS', 'TSh'),
            array('Tongan paʻanga', 'TOP', 'T$'),
            array('Tunisian dinar', 'TND', 'DT'),
            array('Turkmenistani manat', 'TMT', 'T'),
            array('Ugandan shilling', 'UGX', 'USh'),
            array('United Arab Emirates dirham', 'AED', 'د.إ'),
            array('Vanuatu vatu', 'VUV', 'VT'),
            array('Zambian kwacha', 'ZMW', 'ZK'),
            array('Zimbabwean dollar', 'ZWL', '$')
        ]; 

        foreach ($currecnyLists as $currecnyList) {
            $currency = new Currency;
            $currency->name = $currecnyList[0];
            $currency->code = $currecnyList[1];
            $currency->symbol = $currecnyList[2];
            $currency->save();
        }

        $countryflags = [
            '/storage/bank/111-afghanistan.png',
            '/storage/bank/099-albania.png',
            '/storage/bank/144-algeria.png',
            '/storage/bank/027-american-samoa.png',
            '/storage/bank/045-andorra.png',
            '/storage/bank/117-angola.png',
            '/storage/bank/025-anguilla.png',
            '/storage/bank/antarctica.png',
            '/storage/bank/075-antigua-and-barbuda.png',
            '/storage/bank/198-argentina.png',
            '/storage/bank/108-armenia.png',
            '/storage/bank/042-aruba.png',
            '/storage/bank/234-australia.png',
            '/storage/bank/003-austria.png',
            '/storage/bank/141-azerbaijan.png',
            '/storage/bank/120-bahamas.png',
            '/storage/bank/138-bahrain.png',
            '/storage/bank/147-bangladesh.png',
            '/storage/bank/084-barbados.png',
            '/storage/bank/135-belarus.png',
            '/storage/bank/165-belgium.png',
            '/storage/bank/078-belize.png',
            '/storage/bank/060-benin.png',
            '/storage/bank/081-bermuda.png',
            '/storage/bank/040-bhutan.png',
            '/storage/bank/150-bolivia.png',
            '/storage/bank/132-bosnia-and-herzegovina.png',
            '/storage/bank/126-botswana.png',
            '/storage/bank/143-norway.png',
            '/storage/bank/255-brazil.png',
            '/storage/bank/069-british-indian-ocean-territory.png',
            '/storage/bank/119-brunei.png',
            '/storage/bank/168-bulgaria.png',
            '/storage/bank/090-burkina-faso.png',
            '/storage/bank/057-burundi.png',
            '/storage/bank/159-cambodia.png',
            '/storage/bank/105-cameroon.png',
            '/storage/bank/243-canada.png',
            '/storage/bank/038-cape-verde.png',
            '/storage/bank/051-cayman-islands.png',
            '/storage/bank/036-central-african-republic.png',
            '/storage/bank/066-chad.png',
            '/storage/bank/131-chile.png',
            '/storage/bank/034-china.png',
            '/storage/bank/017-christmas-island.png',
            '/storage/bank/023-cocos-island.png',
            '/storage/bank/177-colombia.png',
            '/storage/bank/029-comoros.png',
            '/storage/bank/157-republic-of-the-congo.png',
            '/storage/bank/249-democratic-republic-of-congo.png',
            '/storage/bank/021-cook-islands.png',
            '/storage/bank/156-costa-rica.png',
            '/storage/bank/161-ivory-coast.png',
            '/storage/bank/164-croatia.png',
            '/storage/bank/153-cuba.png',
            '/storage/bank/101-northern-cyprus.png',
            '/storage/bank/149-czech-republic.png',
            '/storage/bank/174-denmark.png',
            '/storage/bank/068-djibouti.png',
            '/storage/bank/186-dominica.png',
            '/storage/bank/047-dominican-republic.png',
            '/storage/bank/140-east-timor.png',
            '/storage/bank/104-ecuador.png',
            '/storage/bank/158-egypt.png',
            '/storage/bank/015-el-salvador.png',
            '/storage/bank/189-equatorial-guinea.png',
            '/storage/bank/065-eritrea.png',
            '/storage/bank/008-estonia.png',
            '/storage/bank/005-ethiopia.png',
            '/storage/bank/193-norfolk-island.png',
            '/storage/bank/215-falkland-islands.png',
            '/storage/bank/122-faroe-islands.png',
            '/storage/bank/137-fiji.png',
            '/storage/bank/125-finland.png',
            '/storage/bank/195-france.png',
            '/storage/bank/french-guiana.png',
            '/storage/bank/180-french-polynesia.png',
            '/storage/bank/frecnh_southern_territories.png',
            '/storage/bank/059-gabon.png',
            '/storage/bank/146-gambia.png',
            '/storage/bank/256-georgia.png',
            '/storage/bank/162-germany.png',
            '/storage/bank/053-ghana.png',
            '/storage/bank/213-gibraltar.png',
            '/storage/bank/170-greece.png',
            '/storage/bank/113-greenland.png',
            '/storage/bank/210-grenada.png',
            '/storage/bank/guadeloupe.gif',
            '/storage/bank/207-guam.png',
            '/storage/bank/098-guatemala.png',
            '/storage/bank/204-guernsey.png',
            '/storage/bank/110-guinea.png',
            '/storage/bank/056-guinea-bissau.png',
            '/storage/bank/guyana.png',
            '/storage/bank/185-haiti.png',
            '/storage/bank/234-australia.png',
            '/storage/bank/024-honduras.png',
            '/storage/bank/183-hong-kong.png',
            '/storage/bank/115-hungary.png',
            '/storage/bank/080-iceland.png',
            '/storage/bank/246-india.png',
            '/storage/bank/209-indonesia.png',
            '/storage/bank/136-iran.png',
            '/storage/bank/020-iraq.png',
            '/storage/bank/179-ireland.png',
            '/storage/bank/155-israel.png',
            '/storage/bank/013-italy.png',
            '/storage/bank/037-jamaica.png',
            '/storage/bank/063-japan.png',
            '/storage/bank/245-jersey.png',
            '/storage/bank/077-jordan.png',
            '/storage/bank/074-kazakhstan.png',
            '/storage/bank/067-kenya.png',
            '/storage/bank/261-kiribati.png',
            '/storage/bank/030-north-korea.png',
            '/storage/bank/094-south-korea.png',
            '/storage/bank/107-kwait.png',
            '/storage/bank/152-kyrgyzstan.png',
            '/storage/bank/112-laos.png',
            '/storage/bank/044-latvia.png',
            '/storage/bank/018-lebanon.png',
            '/storage/bank/176-lesotho.png',
            '/storage/bank/169-liberia.png',
            '/storage/bank/231-libya.png',
            '/storage/bank/134-liechtenstein.png',
            '/storage/bank/064-lithuania.png',
            '/storage/bank/035-luxembourg.png',
            '/storage/bank/macau.png',
            '/storage/bank/236-republic-of-macedonia.png',
            '/storage/bank/242-madagascar.png',
            '/storage/bank/214-malawi.png',
            '/storage/bank/118-malasya.png',
            '/storage/bank/225-maldives.png',
            '/storage/bank/173-mali.png',
            '/storage/bank/194-malta.png',
            '/storage/bank/219-isle-of-man.png',
            '/storage/bank/103-marshall-island.png',
            '/storage/bank/201-martinique.png',
            '/storage/bank/050-mauritania.png',
            '/storage/bank/001-mauritius.png',
            '/storage/bank/195-france.png',
            '/storage/bank/252-mexico.png',
            '/storage/bank/046-micronesia.png',
            '/storage/bank/212-moldova.png',
            '/storage/bank/039-monaco.png',
            '/storage/bank/258-mongolia.png',
            '/storage/bank/043-montserrat.png',
            '/storage/bank/166-morocco.png',
            '/storage/bank/096-mozambique.png',
            '/storage/bank/058-myanmar.png',
            '/storage/bank/062-namibia.png',
            '/storage/bank/228-nauru.png',
            '/storage/bank/016-nepal.png',
            '/storage/bank/netherlands-antilles.png',
            '/storage/bank/237-netherlands.png',
            '/storage/bank/Nouvelle-caledonie_Drapeau_Flag_Bandiera.jpeg',
            '/storage/bank/121-new-zealand.png',
            '/storage/bank/007-nicaragua.png',
            '/storage/bank/086-nigeria.png',
            '/storage/bank/086-nigeria.png',
            '/storage/bank/182-niue.png',
            '/storage/bank/193-norfolk-island.png',
            '/storage/bank/160-northern-marianas-islands.png',
            '/storage/bank/143-norway.png',
            '/storage/bank/004-oman.png',
            '/storage/bank/100-pakistan.png',
            '/storage/bank/178-palau.png',
            '/storage/bank/palestinian.png',
            '/storage/bank/106-panama.png',
            '/storage/bank/163-papua-new-guinea.png',
            '/storage/bank/041-paraguay.png',
            '/storage/bank/188-peru.png',
            '/storage/bank/192-philippines.png',
            '/storage/bank/095-pitcairn-islands.png',
            '/storage/bank/211-poland.png',
            '/storage/bank/224-portugal.png',
            '/storage/bank/028-puerto-rico.png',
            '/storage/bank/qatar.png',
            '/storage/bank/Reunion.jpeg',
            '/storage/bank/109-romania.png',
            '/storage/bank/248-russia.png',
            '/storage/bank/206-rwanda.png',
            '/storage/bank/saint.png',
            '/storage/bank/033-saint-kitts-and-nevis.png',
            '/storage/bank/172-st-lucia.png',
            '/storage/bank/saint_pierre_and_miquelon.png',
            '/storage/bank/241-st-vincent-and-the-grenadines.png',
            '/storage/bank/251-samoa.png',
            '/storage/bank/097-san-marino.png',
            '/storage/bank/012-sao-tome-and-prince.png',
            '/storage/bank/133-saudi-arabia.png',
            '/storage/bank/227-senegal.png',
            '/storage/bank/071-serbia.png',
            '/storage/bank/253-seychelles.png',
            '/storage/bank/092-sierra-leone.png',
            '/storage/bank/230-singapore.png',
            '/storage/bank/091-slovakia.png',
            '/storage/bank/010-slovenia.png',
            '/storage/bank/260-united-kingdom.png',
            '/storage/bank/085-solomon-islands.png',
            '/storage/bank/083-somalia.png',
            '/storage/bank/200-south-africa.png',
            '/storage/bank/south_georgia.png',
            '/storage/bank/244-south-sudan.png',
            '/storage/bank/128-spain.png',
            '/storage/bank/127-sri-lanka.png',
            '/storage/bank/199-sudan.png',
            '/storage/bank/076-suriname.png',
            '/storage/bank/143-norway.png',
            '/storage/bank/154-swaziland.png',
            '/storage/bank/184-sweden.png',
            '/storage/bank/205-switzerland.png',
            '/storage/bank/022-syria.png',
            '/storage/bank/202-taiwan.png',
            '/storage/bank/196-tajikistan.png',
            '/storage/bank/006-tanzania.png',
            '/storage/bank/238-thailand.png',
            '/storage/bank/073-togo.png',
            '/storage/bank/235-tokelau.png',
            '/storage/bank/191-tonga.png',
            '/storage/bank/181-trinidad-and-tobago.png',
            '/storage/bank/049-tunisia.png',
            '/storage/bank/218-turkey.png',
            '/storage/bank/229-turkmenistan.png',
            '/storage/bank/223-turks-and-caicos.png',
            '/storage/bank/070-tuvalu-1.png',
            '/storage/bank/009-uganda.png',
            '/storage/bank/145-ukraine.png',
            '/storage/bank/151-united-arab-emirates.png',
            '/storage/bank/260-united-kingdom.png',
            '/storage/bank/united-states.png',
            '/storage/bank/united-states.png',
            '/storage/bank/088-uruguay.png',
            '/storage/bank/190-uzbekistn.png',
            '/storage/bank/187-vanuatu.png',
            '/storage/bank/124-vatican-city.png',
            '/storage/bank/139-venezuela.png',
            '/storage/bank/220-vietnam.png',
            '/storage/bank/114-british-virgin-islands.png',
            '/storage/bank/217-virgin-islands.png',
            '/storage/bank/Flag_of_Wallis_and_Futuna.png',
            '/storage/bank/western.png',
            '/storage/bank/232-yemen.png',
            '/storage/bank/yugoslavia.png',
            '/storage/bank/032-zambia.png',
            '/storage/bank/011-zimbabwe.png',
        ];

        $countries = Country::all();

        foreach ($countries as $key => $country) {

            $data = array(
                'flag'  =>  $countryflags[$key],
            );

            Country::where('id',$country->id)->update($data);

            
        }
    }
}
