<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Package;
use Faker;

class PackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $packageLists = [
            // array('First Installment ( June, July, August )', '37500', 'ကျောင်းအပ်နှံချိန်', 1),
            // array('Second Installment ( September, October )', '37500', 'သြဂုတ်လအတွင်း', 1),
            // array('Third Installment ( November, December )', '37500', 'အောက်တိုဘာလအတွင်း', 1),
            // array('Fourth Installment ( January, February', '37500', 'ဒီဇင်ဘာလအတွင်း', 1),
            // array('First Installment ( June, July, August )', '42500', 'ကျောင်းအပ်နှံချိန်', 2),
            // array('Second Installment ( September, October )', '42500', 'သြဂုတ်လအတွင်း', 2),
            // array('Third Installment ( November, December )', '42500', 'အောက်တိုဘာလအတွင်း', 2),
            // array('Fourth Installment ( January, February', '42500', 'ဒီဇင်ဘာလအတွင်း', 2),
            // array('First Installment ( June, July, August )', '42500', 'ကျောင်းအပ်နှံချိန်', 3),
            // array('Second Installment ( September, October )', '42500', 'သြဂုတ်လအတွင်း', 3),
            // array('Third Installment ( November, December )', '42500', 'အောက်တိုဘာလအတွင်း', 3),
            // array('Fourth Installment ( January, February', '42500', 'ဒီဇင်ဘာလအတွင်း', 3),
            // array('First Installment ( June, July, August )', '47500', 'ကျောင်းအပ်နှံချိန်', 4),
            // array('Second Installment ( September, October )', '47500', 'သြဂုတ်လအတွင်း', 4),
            // array('Third Installment ( November, December )', '47500', 'အောက်တိုဘာလအတွင်း', 4),
            // array('Fourth Installment ( January, February', '47500', 'ဒီဇင်ဘာလအတွင်း', 4),
            // array('First Installment ( June, July, August )', '47500', 'ကျောင်းအပ်နှံချိန်', 5),
            // array('Second Installment ( September, October )', '47500', 'သြဂုတ်လအတွင်း', 5),
            // array('Third Installment ( November, December )', '47500', 'အောက်တိုဘာလအတွင်း', 5),
            // array('Fourth Installment ( January, February', '47500', 'ဒီဇင်ဘာလအတွင်း', 5),
            // array('First Installment ( June, July, August )', '50000', 'ကျောင်းအပ်နှံချိန်', 6),
            // array('Second Installment ( September, October )', '50000', 'သြဂုတ်လအတွင်း', 6),
            // array('Third Installment ( November, December )', '50000', 'အောက်တိုဘာလအတွင်း', 6),
            // array('Fourth Installment ( January, February', '50000', 'ဒီဇင်ဘာလအတွင်း', 6),
            // array('First Installment ( June, July, August )', '50000', 'ကျောင်းအပ်နှံချိန်', 7),
            // array('Second Installment ( September, October )', '50000', 'သြဂုတ်လအတွင်း', 7),
            // array('Third Installment ( November, December )', '50000', 'အောက်တိုဘာလအတွင်း', 7),
            // array('Fourth Installment ( January, February', '50000', 'ဒီဇင်ဘာလအတွင်း', 7),
            // array('First Installment ( June, July, August )', '50000', 'ကျောင်းအပ်နှံချိန်', 8),
            // array('Second Installment ( September, October )', '50000', 'သြဂုတ်လအတွင်း', 8),
            // array('Third Installment ( November, December )', '50000', 'အောက်တိုဘာလအတွင်း', 8),
            // array('Fourth Installment ( January, February', '50000', 'ဒီဇင်ဘာလအတွင်း', 8),
            // array('First Installment ( June, July, August )', '55000', 'ကျောင်းအပ်နှံချိန်', 9),
            // array('Second Installment ( September, October )', '55000', 'သြဂုတ်လအတွင်း', 9),
            // array('Third Installment ( November, December )', '55000', 'အောက်တိုဘာလအတွင်း', 9),
            // array('Fourth Installment ( January, February', '55000', 'ဒီဇင်ဘာလအတွင်း', 9),
            // array('First Installment ( June, July, August )', '55000', 'ကျောင်းအပ်နှံချိန်', 10),
            // array('Second Installment ( September, October )', '55000', 'သြဂုတ်လအတွင်း', 10),
            // array('Third Installment ( November, December )', '55000', 'အောက်တိုဘာလအတွင်း', 10),
            // array('Fourth Installment ( January, February', '55000', 'ဒီဇင်ဘာလအတွင်း', 10),
            // array('First Installment ( June, July, August )', '75000', 'ကျောင်းအပ်နှံချိန်', 11),
            // array('Second Installment ( September, October )', '75000', 'သြဂုတ်လအတွင်း', 11),
            // array('Third Installment ( November, December )', '75000', 'အောက်တိုဘာလအတွင်း', 11),
            // array('Fourth Installment ( January, February', '75000', 'ဒီဇင်ဘာလအတွင်း', 11),
            // array('First Installment ( June, July, August )', '75000', 'ကျောင်းအပ်နှံချိန်', 12),
            // array('Second Installment ( September, October )', '75000', 'သြဂုတ်လအတွင်း', 12),
            // array('Third Installment ( November, December )', '75000', 'အောက်တိုဘာလအတွင်း', 12),
            // array('Fourth Installment ( January, February', '75000', 'ဒီဇင်ဘာလအတွင်း', 12),
            // array('First Installment ( June, July, August )', '75000', 'ကျောင်းအပ်နှံချိန်', 13),
            // array('Second Installment ( September, October )', '75000', 'သြဂုတ်လအတွင်း', 13),
            // array('Third Installment ( November, December )', '75000', 'အောက်တိုဘာလအတွင်း', 13),
            // array('Fourth Installment ( January, February', '75000', 'ဒီဇင်ဘာလအတွင်း', 13)

            array('First Installment ( June, July, August )', '37500', 'ကျောင်းအပ်နှံချိန်', 14),
            array('Second Installment ( September, October )', '37500', 'သြဂုတ်လအတွင်း', 14),
            array('Third Installment ( November, December )', '37500', 'အောက်တိုဘာလအတွင်း', 14),
            array('Fourth Installment ( January, February', '37500', 'ဒီဇင်ဘာလအတွင်း', 14),
            array('First Installment ( June, July, August )', '42500', 'ကျောင်းအပ်နှံချိန်', 15),
            array('Second Installment ( September, October )', '42500', 'သြဂုတ်လအတွင်း', 15),
            array('Third Installment ( November, December )', '42500', 'အောက်တိုဘာလအတွင်း', 15),
            array('Fourth Installment ( January, February', '42500', 'ဒီဇင်ဘာလအတွင်း', 15),
            array('First Installment ( June, July, August )', '42500', 'ကျောင်းအပ်နှံချိန်', 16),
            array('Second Installment ( September, October )', '42500', 'သြဂုတ်လအတွင်း', 16),
            array('Third Installment ( November, December )', '42500', 'အောက်တိုဘာလအတွင်း', 16),
            array('Fourth Installment ( January, February', '42500', 'ဒီဇင်ဘာလအတွင်း', 16),
            array('First Installment ( June, July, August )', '47500', 'ကျောင်းအပ်နှံချိန်', 17),
            array('Second Installment ( September, October )', '47500', 'သြဂုတ်လအတွင်း', 17),
            array('Third Installment ( November, December )', '47500', 'အောက်တိုဘာလအတွင်း', 17),
            array('Fourth Installment ( January, February', '47500', 'ဒီဇင်ဘာလအတွင်း', 17),
            array('First Installment ( June, July, August )', '47500', 'ကျောင်းအပ်နှံချိန်', 18),
            array('Second Installment ( September, October )', '47500', 'သြဂုတ်လအတွင်း', 18),
            array('Third Installment ( November, December )', '47500', 'အောက်တိုဘာလအတွင်း', 18),
            array('Fourth Installment ( January, February', '47500', 'ဒီဇင်ဘာလအတွင်း', 18),
            array('First Installment ( June, July, August )', '50000', 'ကျောင်းအပ်နှံချိန်', 19),
            array('Second Installment ( September, October )', '50000', 'သြဂုတ်လအတွင်း', 19),
            array('Third Installment ( November, December )', '50000', 'အောက်တိုဘာလအတွင်း', 19),
            array('Fourth Installment ( January, February', '50000', 'ဒီဇင်ဘာလအတွင်း', 19),
            array('First Installment ( June, July, August )', '50000', 'ကျောင်းအပ်နှံချိန်', 20),
            array('Second Installment ( September, October )', '50000', 'သြဂုတ်လအတွင်း', 20),
            array('Third Installment ( November, December )', '50000', 'အောက်တိုဘာလအတွင်း', 20),
            array('Fourth Installment ( January, February', '50000', 'ဒီဇင်ဘာလအတွင်း', 20),
            array('First Installment ( June, July, August )', '50000', 'ကျောင်းအပ်နှံချိန်', 21),
            array('Second Installment ( September, October )', '50000', 'သြဂုတ်လအတွင်း', 21),
            array('Third Installment ( November, December )', '50000', 'အောက်တိုဘာလအတွင်း', 21),
            array('Fourth Installment ( January, February', '50000', 'ဒီဇင်ဘာလအတွင်း', 21),
            array('First Installment ( June, July, August )', '55000', 'ကျောင်းအပ်နှံချိန်', 22),
            array('Second Installment ( September, October )', '55000', 'သြဂုတ်လအတွင်း', 22),
            array('Third Installment ( November, December )', '55000', 'အောက်တိုဘာလအတွင်း', 22),
            array('Fourth Installment ( January, February', '55000', 'ဒီဇင်ဘာလအတွင်း', 22),
            array('First Installment ( June, July, August )', '55000', 'ကျောင်းအပ်နှံချိန်', 23),
            array('Second Installment ( September, October )', '55000', 'သြဂုတ်လအတွင်း', 23),
            array('Third Installment ( November, December )', '55000', 'အောက်တိုဘာလအတွင်း', 23),
            array('Fourth Installment ( January, February', '55000', 'ဒီဇင်ဘာလအတွင်း', 23),
            array('First Installment ( June, July, August )', '75000', 'ကျောင်းအပ်နှံချိန်', 24),
            array('Second Installment ( September, October )', '75000', 'သြဂုတ်လအတွင်း', 24),
            array('Third Installment ( November, December )', '75000', 'အောက်တိုဘာလအတွင်း', 24),
            array('Fourth Installment ( January, February', '75000', 'ဒီဇင်ဘာလအတွင်း', 24),
            array('First Installment ( June, July, August )', '75000', 'ကျောင်းအပ်နှံချိန်', 25),
            array('Second Installment ( September, October )', '75000', 'သြဂုတ်လအတွင်း', 25),
            array('Third Installment ( November, December )', '75000', 'အောက်တိုဘာလအတွင်း', 25),
            array('Fourth Installment ( January, February', '75000', 'ဒီဇင်ဘာလအတွင်း', 25),
            array('First Installment ( June, July, August )', '75000', 'ကျောင်းအပ်နှံချိန်', 26),
            array('Second Installment ( September, October )', '75000', 'သြဂုတ်လအတွင်း', 26),
            array('Third Installment ( November, December )', '75000', 'အောက်တိုဘာလအတွင်း', 26),
            array('Fourth Installment ( January, February', '75000', 'ဒီဇင်ဘာလအတွင်း', 26),

            // array('First Installment ( June, July, August )', '37500', 'ကျောင်းအပ်နှံချိန်', 27),
            // array('Second Installment ( September, October )', '37500', 'သြဂုတ်လအတွင်း', 27),
            // array('Third Installment ( November, December )', '37500', 'အောက်တိုဘာလအတွင်း', 27),
            // array('Fourth Installment ( January, February', '37500', 'ဒီဇင်ဘာလအတွင်း', 27),
            // array('First Installment ( June, July, August )', '42500', 'ကျောင်းအပ်နှံချိန်', 28),
            // array('Second Installment ( September, October )', '42500', 'သြဂုတ်လအတွင်း', 28),
            // array('Third Installment ( November, December )', '42500', 'အောက်တိုဘာလအတွင်း', 28),
            // array('Fourth Installment ( January, February', '42500', 'ဒီဇင်ဘာလအတွင်း', 28),
            // array('First Installment ( June, July, August )', '42500', 'ကျောင်းအပ်နှံချိန်', 29),
            // array('Second Installment ( September, October )', '42500', 'သြဂုတ်လအတွင်း', 29),
            // array('Third Installment ( November, December )', '42500', 'အောက်တိုဘာလအတွင်း', 29),
            // array('Fourth Installment ( January, February', '42500', 'ဒီဇင်ဘာလအတွင်း', 29),
            // array('First Installment ( June, July, August )', '47500', 'ကျောင်းအပ်နှံချိန်', 30),
            // array('Second Installment ( September, October )', '47500', 'သြဂုတ်လအတွင်း', 30),
            // array('Third Installment ( November, December )', '47500', 'အောက်တိုဘာလအတွင်း', 30),
            // array('Fourth Installment ( January, February', '47500', 'ဒီဇင်ဘာလအတွင်း', 30),
            // array('First Installment ( June, July, August )', '47500', 'ကျောင်းအပ်နှံချိန်', 31),
            // array('Second Installment ( September, October )', '47500', 'သြဂုတ်လအတွင်း', 31),
            // array('Third Installment ( November, December )', '47500', 'အောက်တိုဘာလအတွင်း', 31),
            // array('Fourth Installment ( January, February', '47500', 'ဒီဇင်ဘာလအတွင်း', 31),
            // array('First Installment ( June, July, August )', '50000', 'ကျောင်းအပ်နှံချိန်', 32),
            // array('Second Installment ( September, October )', '50000', 'သြဂုတ်လအတွင်း', 32),
            // array('Third Installment ( November, December )', '50000', 'အောက်တိုဘာလအတွင်း', 32),
            // array('Fourth Installment ( January, February', '50000', 'ဒီဇင်ဘာလအတွင်း', 32),
            // array('First Installment ( June, July, August )', '50000', 'ကျောင်းအပ်နှံချိန်', 33),
            // array('Second Installment ( September, October )', '50000', 'သြဂုတ်လအတွင်း', 33),
            // array('Third Installment ( November, December )', '50000', 'အောက်တိုဘာလအတွင်း', 33),
            // array('Fourth Installment ( January, February', '50000', 'ဒီဇင်ဘာလအတွင်း', 33),
            // array('First Installment ( June, July, August )', '50000', 'ကျောင်းအပ်နှံချိန်', 34),
            // array('Second Installment ( September, October )', '50000', 'သြဂုတ်လအတွင်း', 34),
            // array('Third Installment ( November, December )', '50000', 'အောက်တိုဘာလအတွင်း', 34),
            // array('Fourth Installment ( January, February', '50000', 'ဒီဇင်ဘာလအတွင်း', 34),
            // array('First Installment ( June, July, August )', '55000', 'ကျောင်းအပ်နှံချိန်', 35),
            // array('Second Installment ( September, October )', '55000', 'သြဂုတ်လအတွင်း', 35),
            // array('Third Installment ( November, December )', '55000', 'အောက်တိုဘာလအတွင်း', 35),
            // array('Fourth Installment ( January, February', '55000', 'ဒီဇင်ဘာလအတွင်း', 35),
            // array('First Installment ( June, July, August )', '55000', 'ကျောင်းအပ်နှံချိန်', 36),
            // array('Second Installment ( September, October )', '55000', 'သြဂုတ်လအတွင်း', 36),
            // array('Third Installment ( November, December )', '55000', 'အောက်တိုဘာလအတွင်း', 36),
            // array('Fourth Installment ( January, February', '55000', 'ဒီဇင်ဘာလအတွင်း', 36),
            // array('First Installment ( June, July, August )', '75000', 'ကျောင်းအပ်နှံချိန်', 37),
            // array('Second Installment ( September, October )', '75000', 'သြဂုတ်လအတွင်း', 37),
            // array('Third Installment ( November, December )', '75000', 'အောက်တိုဘာလအတွင်း', 37),
            // array('Fourth Installment ( January, February', '75000', 'ဒီဇင်ဘာလအတွင်း', 37),
            // array('First Installment ( June, July, August )', '75000', 'ကျောင်းအပ်နှံချိန်', 38),
            // array('Second Installment ( September, October )', '75000', 'သြဂုတ်လအတွင်း', 38),
            // array('Third Installment ( November, December )', '75000', 'အောက်တိုဘာလအတွင်း', 38),
            // array('Fourth Installment ( January, February', '75000', 'ဒီဇင်ဘာလအတွင်း', 38),
            // array('First Installment ( June, July, August )', '75000', 'ကျောင်းအပ်နှံချိန်', 39),
            // array('Second Installment ( September, October )', '75000', 'သြဂုတ်လအတွင်း', 39),
            // array('Third Installment ( November, December )', '75000', 'အောက်တိုဘာလအတွင်း', 39),
            // array('Fourth Installment ( January, February', '75000', 'ဒီဇင်ဘာလအတွင်း', 39)
        ];

        foreach($packageLists as $packageList){
            $package = new Package;
            $package->installment = $packageList[0];
            $package->amount = $packageList[1];
            $package->description = $packageList[2];
            $package->section_id = $packageList[3];
            $package->user_id = 2;
            $package->school_id = 1;
            $package->save();
        }
    }
}
